name: hauberk
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  malison: '^0.13.0'
  markdown: any
  path: any
  piecemeal: '^1.0.0'
dev_dependencies:
  analyzer: '^5.0.0'
  build_runner: '^2.2.1'
  build_web_compilers: '^3.2.6'
  test: '^1.21.6'
